/**
 * Standardized Socket Event Schema
 * This file defines all socket events and their payload structures
 * to ensure consistency between backend and frontend
 */

/**
 * Versioning for socket events.
 * Increment this when breaking changes to event contracts are introduced.
 */
export const SOCKET_EVENTS_VERSION = "1.0";

// Base event response structure
export interface BaseEventResponse {
  /**
   * Whether the event operation completed successfully.
   */
  success: boolean;
  /**
   * Optional human readable message.
   */
  message?: string;
  /**
   * ISO timestamp generated by the server when the response was created.
   */
  timestamp: string;
  /**
   * Optional classification for error types.
   */
  type?:
    | "validation_error"
    | "server_error"
    | "auth_error"
    | "not_found"
    | "permission_denied";
}

/**
 * Standard success response envelope.
 * @template T - Shape of the data payload.
 */
export interface SuccessResponse<T = any> extends BaseEventResponse {
  success: true;
  data: T;
}

/**
 * Standard error response envelope.
 */
export interface ErrorResponse extends BaseEventResponse {
  success: false;
  error: string;
  code?: string;
}

// Message Events

/**
 * Payload used to send a message to another user or conversation.
 */
export interface MessageSendPayload {
  recipientId: string;
  content: string;
  type?: "text" | "image" | "file" | "audio" | "video";
  replyToId?: string;
  conversationId?: string;
  tempId?: string; // Optional client-generated id for optimistic reconciliation
}

/**
 * Response returned when a message is successfully processed by the server.
 */
export interface MessageSentResponse extends SuccessResponse {
  data: {
    message: Message;
    conversationId: string;
    isNewConversation: boolean;
    deliveryId: string;
  };
}

/**
 * Emitted to other participants when a new message is created.
 */
export interface MessageNewPayload {
  message: Message;
  conversationId: string;
  isNewConversation?: boolean;
}

/**
 * Actual message data sent by backend via socket
 */
export interface SocketMessageData {
  id: string;
  content: string;
  timestamp: string;
  sender: User;
  senderType: "user" | "admin";
  conversationId: string;
  tempId?: string; // echoed client temp id for reconciliation
}

/**
 * Payload to mark a message as read.
 */
export interface MessageReadPayload {
  messageId: string;
  conversationId: string;
}

/**
 * Payload to mark multiple messages as read.
 * Alias for MessageReadPayload but supports multiple message IDs.
 */
export interface MessagesReadPayload {
  messageIds: string[];
  conversationId: string;
}

/**
 * Payload to request deletion of a message.
 */
export interface MessageDeletePayload {
  messageId: string;
  conversationId: string;
}

/**
 * Delivery information broadcasted when a message is delivered to recipient device.
 */
export interface MessageDeliveredPayload {
  messageId: string;
  conversationId: string;
  deliveredAt: string;
  recipientId: string;
}

/**
 * Client confirmation that it received a delivery notification.
 */
export interface MessageDeliveryConfirmPayload {
  messageId: string;
  deliveryId: string;
}

/**
 * Acknowledgement payload for message read/delivery/receipt flows.
 */
export interface MessageAckPayload {
  messageId: string;
  conversationId?: string;
  ackAt: string;
  recipientId?: string;
  type?: "delivered" | "read" | "received";
}

// Conversation Events

/**
 * Payload to join a conversation room.
 */
export interface ConversationJoinPayload {
  conversationId: string;
}

/**
 * Response after successfully joining a conversation.
 */
export interface ConversationJoinedResponse extends SuccessResponse {
  data: {
    conversationId: string;
  };
}

/**
 * Request to fetch conversation messages (pagination supported).
 */
export interface ConversationMessagesPayload {
  conversationId: string;
  page?: number;
  limit?: number;
}

/**
 * Response containing messages for a conversation along with pagination meta.
 */
export interface ConversationMessagesResponse extends SuccessResponse {
  data: {
    messages: Message[];
    pagination: {
      page: number;
      limit: number;
      total: number;
      hasMore: boolean;
    };
  };
}

/**
 * When a conversation is created on the server.
 */
export interface ConversationCreatedPayload {
  conversation: Conversation;
  otherParticipant: User;
}

/**
 * Response listing conversations for a user.
 */
export interface ConversationsListResponse extends SuccessResponse {
  data: {
    conversations: Conversation[];
  };
}

/**
 * Payload to leave a conversation (stop receiving events for it).
 */
export interface ConversationLeavePayload {
  conversationId: string;
  userId?: string;
}

// Typing Events

/**
 * Typing start indicator payload.
 */
export interface TypingStartPayload {
  conversationId?: string;
  recipientId?: string;
}

/**
 * Typing stop indicator payload.
 */
export interface TypingStopPayload {
  conversationId?: string;
  recipientId?: string;
}

/**
 * Standardized typing user payload broadcasted to conversation participants.
 */
export interface TypingUserPayload {
  userId: string;
  username: string;
  conversationId: string;
  isTyping: boolean;
}

// Handshake & Auth Events

/**
 * Handshake request payload sent by the client during initial connect.
 */
export interface HandshakeRequestPayload {
  timestamp: number;
  clientId: string;
  attempt: number;
}

/**
 * Handshake response returned by the server upon successful handshake.
 */
export interface HandshakeResponse extends SuccessResponse {
  data: {
    userId: string;
    username: string;
    serverTime: string;
  };
}

/**
 * Authentication request payload - used when the client supplies tokens during connection or refresh.
 */
export interface AuthRequestPayload {
  token?: string;
  refreshToken?: string;
  clientId?: string;
}

/**
 * Authentication response payload containing refreshed tokens and user info.
 */
export interface AuthResponsePayload {
  userId: string;
  username: string;
  token: string;
  refreshToken?: string;
  expiresAt?: string;
}

/**
 * Response envelope for authentication operations.
 */
export interface AuthResponse extends SuccessResponse<AuthResponsePayload> {}

/**
 * Emitted when authentication fails on the socket layer.
 */
export interface AuthErrorPayload {
  reason: string;
  code?: string;
}

// Presence / User Events

/**
 * Response containing currently online users.
 */
export interface OnlineUsersResponse extends SuccessResponse {
  data: {
    users: OnlineUser[];
  };
}

/**
 * Payload broadcasted when a single user comes online.
 */
export interface UserOnlinePayload {
  user: OnlineUser;
  since: string;
}

/**
 * Payload broadcasted when a user goes offline.
 */
export interface UserOfflinePayload {
  userId: string;
  lastSeen?: string;
}

/**
 * Generic users update broadcast payload.
 */
export interface UsersUpdatedPayload {
  added?: OnlineUser[];
  removed?: { id: string; lastSeen?: string }[];
  updated?: OnlineUser[];
}

// Notification Events

/**
 * Payload used to create a notification.
 */
export interface NotificationCreatePayload {
  recipientId: string;
  title: string;
  body: string;
  metadata?: Record<string, any>;
  ttl?: number;
}

/**
 * Notification event delivered to clients.
 */
export interface NotificationPayload {
  id: string;
  title: string;
  body: string;
  metadata?: Record<string, any>;
  createdAt: string;
  read?: boolean;
}

// Session / Recovery Events

/**
 * Emitted when a session expires server-side and client needs to re-authenticate.
 */
export interface SessionExpiredPayload {
  userId?: string;
  reason?: string;
}

/**
 * Emitted when a session is recovered (e.g. via token refresh).
 */
export interface SessionRecoveredPayload {
  userId: string;
  recoveredAt: string;
  tokenExpiresAt?: string;
}

// Ping / Health Events

/**
 * Ping payload for latency checks or keepalive.
 */
export interface PingPayload {
  timestamp: number;
  clientId?: string;
}

/**
 * Pong response from server.
 */
export interface PongPayload {
  timestamp: number;
  serverTime: string;
}

// Data Subscription Events

export interface DataSubscribePayload {
  channel: string;
  filters?: Record<string, any>;
  options?: {
    throttleMs?: number;
    heartbeat?: boolean;
  };
}

export interface DataSubscribedPayload {
  channel: string;
  subscriptionId: string;
  success: boolean;
  message?: string;
}

// Data Models

// Database Message interface (matches backend structure)
export interface Message {
  id: string;
  conversation_id: string;
  sender_id: string;
  recipient_id: string;
  content: string;
  type: "text" | "image" | "file" | "audio" | "video";
  reply_to_id?: string;
  senderType?: "user" | "admin"; // Backend compatibility field
  is_read: boolean;
  isRead?: boolean; // Backend compatibility field
  is_deleted: boolean;
  created_at: string;
  updated_at: string;
  timestamp?: string; // Backend compatibility field
  read_at?: string;
  preview?: string;
  sender?: User;
  recipient?: User;
  replyTo?: Message;
}

// Frontend Message interface (used in React components)
export interface FrontendMessage {
  id: string;
  conversationId: string;
  content: string;
  timestamp: string;
  sender: User;
  senderType: "user" | "admin";
  isRead: boolean;
  readAt?: string | null;
  isDelivered?: boolean;
  deliveredAt?: string | null;
}

export interface Conversation {
  id: string;
  participant1_id: string;
  participant2_id: string;
  last_message_id?: string;
  created_at: string;
  updated_at: string;
  participant1?: User;
  participant2?: User;
  lastMessage?: Message;
  otherParticipant?: User;
  unread_count?: number;
}

export interface User {
  id: string;
  username: string;
  name: string;
  email?: string;
  is_active?: boolean;
  role?:
    | "super_admin"
    | "co_admin"
    | "kantor_pusat"
    | "kanwil_djpb"
    | "kppn"
    | "lainnya";
}

export interface OnlineUser {
  id: string;
  username: string;
  name: string;
  lastSeen?: string;
}

// Event Name Constants
export const SOCKET_EVENTS = {
  // Version meta (useful for debugging and conditional handling)
  VERSION: SOCKET_EVENTS_VERSION,

  // Connection Events
  CONNECT: "connect",
  DISCONNECT: "disconnect",
  CONNECT_ERROR: "connect_error",
  ERROR: "error",

  // Health / Keepalive
  PING: "ping",
  PONG: "pong",

  // Handshake & Auth Events
  HANDSHAKE_REQUEST: "handshake:request",
  HANDSHAKE_RESPONSE: "handshake:response",
  AUTH_REQUEST: "auth:request",
  AUTH_RESPONSE: "auth:response",
  AUTH_ERROR: "auth:error",
  SESSION_EXPIRED: "session:expired",
  SESSION_RECOVERED: "session:recovered",

  // Message Events
  MESSAGE_SEND: "message:send",
  MESSAGE_SENT: "message:sent",
  MESSAGE_NEW: "message:new",
  MESSAGE_RECEIVED: "message:received",
  MESSAGE_READ: "message:read",
  MESSAGE_DELETE: "message:delete",
  MESSAGE_DELETED: "message:deleted",
  MESSAGE_DELIVERED: "message:delivered",
  MESSAGE_DELIVERY_CONFIRM: "message:delivery:confirm",
  MESSAGE_ACK: "message:ack",
  MESSAGE_ERROR: "message:error",

  // Conversation Events
  CONVERSATION_JOIN: "conversation:join",
  CONVERSATION_JOINED: "conversation:joined",
  CONVERSATION_LEAVE: "conversation:leave",
  CONVERSATION_LEFT: "conversation:left",
  CONVERSATION_MESSAGES: "conversation:messages",
  CONVERSATION_CREATED: "conversation:created",
  CONVERSATION_ERROR: "conversation:error",
  CONVERSATIONS_GET: "conversations:get",
  CONVERSATIONS_LIST: "conversations:list",
  CONVERSATIONS_UPDATED: "conversations:updated",

  // Typing Events
  TYPING_START: "typing:start",
  TYPING_STOP: "typing:stop",
  TYPING_USER: "typing:user",
  TYPING_ERROR: "typing:error",

  // User / Presence Events
  USERS_GET_ONLINE: "users:get-online",
  USERS_ONLINE: "users:online",
  USER_LOGIN: "user:login",
  USER_ONLINE: "user:online",
  USER_OFFLINE: "user:offline",
  USERS_UPDATED: "users:updated",

  // Notification Events
  NOTIFICATION_CREATE: "notification:create",
  NOTIFICATION_CREATED: "notification:created",
  NOTIFICATION_ERROR: "notification:error",

  // Data Subscription Events
  DATA_SUBSCRIBE: "data:subscribe",
  DATA_SUBSCRIBED: "data:subscribed",
  DATA_UNSUBSCRIBE: "data:unsubscribe",
  DATA_UPDATE: "data:update",
} as const;

// Helper functions for creating standardized responses

/**
 * Create a standardized success response envelope.
 * @param data - Payload data.
 * @param message - Optional human readable message.
 * @returns SuccessResponse<T>
 */
export function createStandardSuccessResponse<T>(
  data: T,
  message?: string
): SuccessResponse<T> {
  return {
    success: true,
    data,
    message,
    timestamp: new Date().toISOString(),
  };
}

/**
 * Create a standardized error response envelope.
 * @param error - Error message.
 * @param type - Optional classification of error.
 * @param code - Optional error code.
 * @returns ErrorResponse
 */
export function createStandardErrorResponse(
  error: string,
  type?: ErrorResponse["type"],
  code?: string
): ErrorResponse {
  return {
    success: false,
    error,
    type,
    code,
    timestamp: new Date().toISOString(),
  };
}

// Legacy aliases for backward compatibility
export const createSuccessResponse = createStandardSuccessResponse;
export const createErrorResponse = createStandardErrorResponse;

// Utility functions

/**
 * Safely formats a time string with validation for messaging timestamps
 * Returns a fallback value for invalid dates
 */
export function formatRelativeTime(
  dateString: string | null | undefined,
  fallback: string = "—"
): string {
  if (!dateString) {
    console.warn("formatRelativeTime: No dateString provided:", dateString);
    return fallback;
  }

  try {
    const date = new Date(dateString);

    // Check if the date is valid
    if (isNaN(date.getTime())) {
      console.warn(`Invalid date string received: ${dateString}`);
      return fallback;
    }

    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / (1000 * 60));
    const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
    const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

    if (diffMins < 1) {
      return "Just now";
    } else if (diffMins < 60) {
      return `${diffMins}m ago`;
    } else if (diffHours < 24) {
      return `${diffHours}h ago`;
    } else if (diffDays === 1) {
      return "Yesterday";
    } else if (diffDays < 7) {
      return `${diffDays}d ago`;
    } else {
      // For older messages, show the date
      return date.toLocaleDateString();
    }
  } catch (error) {
    console.error(`Error formatting relative time: ${dateString}`, error);
    return fallback;
  }
}
